import CrearSolicitudPaquete, {
  SolicitudPaqueteInfo,
} from '@/components/solicitudesPaquetes/CrearSolicitudPaquete';
import SolicitudesPaquetesList from '@/components/solicitudesPaquetes/components/SolicitudesPaqueteList';
import CrearSolicitud, {
  SolicitudServicioInfo,
} from '@/components/solicitudesServicios/CrearSolicitud';
import SolicitudesList from '@/components/solicitudesServicios/SolicitudesList';
import SolicitudesPaginacion from '@/components/solicitudesServicios/SolicitudesPaginacion';
import { ApiService } from '@/services/api.service';
import { Fragment, useEffect, useState } from 'react';
import Swal from 'sweetalert2';

// Generated by https://quicktype.io

export interface ListaSolicitudesPaquetesResponse {
  paginationInfo: {
    totalPages: number;
    totalElements: number;
    currentPage: number;
    currentElements: number;
  };
  elements: SolicitudPaqueteInfo[];
}

const ViajarAhoraPage = () => {
  const [userId] = useState<string>('e9c596b2-780b-4aea-845f-855d2678a8cd');
  const [loading, setLoading] = useState<boolean>(true);
  let [apiService] = useState(new ApiService());
  const [paginacion, setPaginacion] = useState({
    page: 0,
    size: 10,
  });

  const [solicitudesPaquetes, setSolicitudesPaquetes] =
    useState<ListaSolicitudesPaquetesResponse>({
      paginationInfo: {
        totalPages: 0,
        totalElements: 0,
        currentPage: 0,
        currentElements: 0,
      },
      elements: [],
    });

  const { paginationInfo } = solicitudesPaquetes;

  useEffect(() => {
    setLoading(true);
    new Promise((resolve) => {
      setTimeout(() => resolve(''), 100);
    }).then(() => {
      apiService
        .get<ListaSolicitudesPaquetesResponse>(
          '/solicitudes-paquetes',
          {
            ...paginacion,
          },
          true
        )
        .then((data) => {
          setSolicitudesPaquetes(data);
        })
        .catch((err) => {
          return Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: 'No se pudo obtener las solicitudes',
          });
        })
        .finally(() => {
          setLoading(false);
        });
    });
  }, [paginacion]);

  const traerSiguientePagina = () => {
    setPaginacion((paginacion) => ({
      ...paginacion,
      page: paginacion.page + 1,
    }));
  };

  const traerAnteriorPagina = () => {
    setPaginacion((paginacion) => ({
      ...paginacion,
      page: paginacion.page - 1,
    }));
  };

  return (
    <Fragment>
      {loading ? (
        <div className='w-screen h-screen flex justify-center items-center bg-transparent'>
          <div>
            <p className='text-center'>Cargando...</p>
            <img
              src='/images/common/loading.svg'
              alt='loading'
              className='bg-white'
            />
          </div>
        </div>
      ) : (
        <div className='flex flex-row justify-evenly flex-wrap h-screen overflow-y-auto'>
          <div
            style={{ minWidth: '500px', height: '100vh', overflowY: 'auto' }}
          >
            <CrearSolicitudPaquete
              setSolicitudesPaquetes={setSolicitudesPaquetes}
            />
          </div>

          <div
            className='ml-5 overflow-y-auto h-screen w-max flex-grow'
            style={{ minWidth: '500px' }}
          >
            <SolicitudesPaquetesList
              solicitudesPaquetes={solicitudesPaquetes}
              setSolicitudesPaquetes={setSolicitudesPaquetes}
              // activeTab={activeTab}
              // setActiceTab={setActiceTab}
            />
            {paginationInfo.totalElements > 0 && (
              <SolicitudesPaginacion
                paginationInfo={paginationInfo}
                traerSiguientePagina={traerSiguientePagina}
                traerAnteriorPagina={traerAnteriorPagina}
              />
            )}
          </div>
        </div>
      )}
    </Fragment>
  );
};

export default ViajarAhoraPage;

// import Header from '@/components/shared/Header';
// import { useForm } from 'react-hook-form';
// import Swal from 'sweetalert2';
// import { ApiService } from '@/services/api.service';

// const EnviarRecogerPaquete = () => {
//   const {
//     register,
//     formState: { errors },
//     handleSubmit,
//     getValues,
//   } = useForm();
//   const apiService = new ApiService();

//   const onSubmit = async function (data: any) {
//     // await apiService.post(data, 'url endpoint').then((rta:any) =>{
//     //   Swal.fire({title: rta.message, focusConfirm: false, confirmButtonColor: '#3085d6', confirmButtonText: 'Aceptar'})
//     // });
//     window.location.replace('/servicios/usuario/buscandoSocio');
//   };

//   return (
//     <>
//       <div className='m-4 mb-5 overflow-auto m-0 p-0'>
//         <div className='flex items-center justify-center m-0 p-0'>
//           <Header />
//           <div className='max-w-md w-full bg-white rounded-lg shadow-lg'>
//             <div className='mt-24 px-6 m-0 p-0'>
//               <h1 className='text-2xl font-semibold text-center text-gray-500 mt-4 mb-6'>
//                 Enviar o recoger paqute
//               </h1>
//               <form>
//                 <div className='mb-4'>
//                   <label className='block mb-2 text-sm text-gray-600'>
//                     ¿Dónde recogemos el paquete?
//                   </label>
//                   <input
//                     type='text'
//                     id='start'
//                     className='w-full bg-transparent ring-2 ring-gray-300 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500'
//                     required
//                     {...register('start', { required: true })}
//                   />
//                   {errors.start?.type === 'required' && (
//                     <p className='text-red-500'>
//                       Establece un punto de partida
//                     </p>
//                   )}
//                 </div>
//                 <div className='mb-4'>
//                   <label className='block mb-2 text-sm text-gray-600'>
//                     ¿Dónde entregamos el paquete?
//                   </label>
//                   <input
//                     type='text'
//                     id='destiny'
//                     className='w-full bg-transparent ring-2 ring-gray-300 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500'
//                     required
//                     {...register('destiny', { required: true })}
//                   />
//                   {errors.destiny?.type === 'required' && (
//                     <p className='text-red-500'>
//                       Establece un punto de llegada
//                     </p>
//                   )}
//                 </div>
//                 <div className='mb-4'>
//                   <label className='block mb-2 text-sm text-gray-600'>
//                     Dimensiones del paquete
//                   </label>
//                   <input
//                     type='number'
//                     min='0'
//                     id='largo'
//                     placeholder='Largo (cm)'
//                     className='w-full bg-transparent ring-2 ring-gray-300 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500'
//                     required
//                     {...register('largo', {
//                       required: true,
//                       value: 50,
//                       min: 0,
//                     })}
//                   />
//                   {errors.largo?.type === 'required' && (
//                     <p className='text-red-500'>
//                       Dees indicar el largo del paqute
//                     </p>
//                   )}

//                   {errors.largo?.type === 'min' && (
//                     <p className='text-red-500'>
//                       El largo del paquete debe ser mayor a 0
//                     </p>
//                   )}
//                   <input
//                     type='number'
//                     min='0'
//                     id='ancho'
//                     placeholder='Ancho (cm)'
//                     className='w-full bg-transparent ring-2 ring-gray-300 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500'
//                     required
//                     {...register('ancho', {
//                       required: true,
//                       value: 50,
//                       min: 0,
//                     })}
//                   />
//                   {errors.ancho?.type === 'required' && (
//                     <p className='text-red-500'>
//                       Dees indicar las dimensiones del paqute
//                     </p>
//                   )}
//                   {errors.ancho?.type === 'min' && (
//                     <p className='text-red-500'>
//                       El ancho del paquete debe ser mayor a 0
//                     </p>
//                   )}
//                   <input
//                     type='number'
//                     min='0'
//                     id='alto'
//                     placeholder='Alto (cm)'
//                     className='w-full bg-transparent ring-2 ring-gray-300 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500'
//                     required
//                     {...register('alto', { required: true, value: 50, min: 0 })}
//                   />
//                   {errors.alto?.type === 'required' && (
//                     <p className='text-red-500'>
//                       Dees indicar las dimensiones del paqute
//                     </p>
//                   )}
//                   {errors.alto?.type === 'min' && (
//                     <p className='text-red-500'>
//                       El alto del paquete debe ser mayor a 0
//                     </p>
//                   )}
//                 </div>
//                 <div className='mb-4'>
//                   <label className='block mb-2 text-sm text-gray-600'>
//                     Peso del paquete
//                   </label>
//                   <input
//                     type='weight'
//                     id='peso'
//                     className='w-full bg-transparent ring-2 ring-gray-300 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500'
//                     required
//                     {...register('weight', { required: true })}
//                   />
//                   {errors.weight?.type === 'required' && (
//                     <p className='text-red-500'>
//                       Dees indicar el peso del paqute
//                     </p>
//                   )}
//                 </div>
//                 <div className='mb-6'>
//                   <label className='block mb-2 text-sm text-gray-600'>
//                     Hora de recogida
//                   </label>
//                   <input
//                     type='time'
//                     id='time'
//                     className='w-full bg-transparent ring-2 ring-gray-300 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500'
//                     required
//                     {...register('time', { required: true })}
//                   />
//                   {errors.time?.type === 'required' && (
//                     <p className='text-red-500'>
//                       Selecciona la hora en la que debemos recoger el paquete
//                     </p>
//                   )}
//                 </div>
//                 <div className='w-full mb-6 inline-flex items-center'>
//                   <input
//                     type='checkbox'
//                     id='food'
//                     className='form-checkbox w-16'
//                     {...register('food', { required: false })}
//                   />
//                   <label className='ml-2'>Son alimentos o mercado</label>
//                 </div>
//                 <button
//                   onClick={handleSubmit(onSubmit)}
//                   type='submit'
//                   className='my-8 w-full rounded-2xl border-b-4 border-b-blue-600 bg-blue-500 py-2 font-bold text-white hover:bg-blue-400 active:translate-y-[0.125rem] active:bord    er-b-blue-400'
//                 >
//                   Solicitar servicio
//                 </button>
//               </form>
//             </div>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// };
// export default EnviarRecogerPaquete;
